@ResourceUrl = https://localhost:5001/v1/resume
@DbType = lite
@CorrelationId = ff7963bf-26ca-4f99-a987-34163af00300

POST {{ResourceUrl}}
Accept: application/json
Content-Type: application/json
X-DbType: {{DbType}}
X-Correlation-Id: {{CorrelationId}}

{
  "firstName": "John",
  "lastName": "Doe",
  "jobTitle": "Software Developer",
  "companyName": "Acme Inc.",
  "email": "johndoe@domain.com",
  "phoneNumber": "+1234567890",
  "city": "New York",
  "state": "NY",
  "country": "USA"
}
###

GET {{ResourceUrl}}/john-doe-6fae45b
Content-Type: application/json
X-DbType: {{DbType}}
X-Correlation-Id: {{CorrelationId}}

###

PATCH {{ResourceUrl}}/0194d61c-9323-7c29-88fa-c99931ad26d7/handle
Content-Type: application/json
X-Correlation-Id: {{CorrelationId}}

{
  "handle": "johndoe"
}